var taqHome;
(function(){function S(a){return null==a||void 0==a?!0:"string"!=typeof a?!1:0==u(a).length}function u(a){return a.replace(/^\s+|\s+$/gm,"")}function r(a,b){return null==a||void 0==a?a:u(a).length>b?a.substring(0,b-3)+"...":a}function da(a){return a.replace(/<br.*?>/g," ")}function T(a){var b=g.cookie.indexOf(a+"=");if(-1==b)return null;b=b+a.length+1;a=g.cookie.indexOf(";",b);-1==a&&(a=g.cookie.length);return unescape(g.cookie.substring(b,a))}function U(a,b,c,d,e){null==e||void 0==e||0==("string"!=
typeof e?!1:0<e.length)?g.cookie=a+"="+b+"; path="+c+"; expires="+d:g.cookie=a+"="+b+"; path="+c+"; domain="+e+"; expires="+d}function V(a){if(S(a)||"undefined"==a||"string"!=typeof a)return!0;if(24<a.length)return s("length="+a.length+": "+a),!0;var b=a.indexOf("_");if(-1==b||4<b)return s("first underline index="+b+": "+a),!0;var c=a.indexOf("_",b+1);if(-1==c||1==c-b)return s("second underline index="+c+": "+a),!0;b=a.indexOf("_",c+1);return-1!=b?(s("third underline index="+b+": "+a),!0):!1}function W(a){var b=
parseInt(Math.floor(1E3*Math.random()+1)+""+Math.floor(1E3*Math.random()+1));return String(b.toString(36).concat("_").concat(a).concat("_").concat((new Date).valueOf().toString(36)))}function ea(a){var b=parseInt(Math.floor(1E3*Math.random()+1)+""+Math.floor(1E3*Math.random()+1));return String((a+"").concat("_").concat((new Date).valueOf().toString(36)).concat("_").concat(b.toString(36)))}function fa(a,b){var c=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return c?c[3]:"null"}function s(a){if(window.console&&
console.log)try{console.log(a)}catch(b){}}function ga(){var a;try{return a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),a.GetVariable("$version")}catch(b){}try{return a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),version="WIN 6,0,21,0",a.AllowScriptAccess="always",a.GetVariable("$version")}catch(c){}try{return a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),a.GetVariable("$version")}catch(d){}try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),"WIN 3,0,18,0"}catch(e){}try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),
"WIN 2,0,0,11"}catch(f){return"-1"}}function ha(){var a="Shockwave Flash ";if(navigator.plugins&&0<navigator.plugins.length){var b=navigator.plugins["Shockwave Flash"];if(!b)return"-1";try{if(void 0!=b.version)return b.version}catch(c){}b=b.description;return-1!=b.indexOf(a)?b.substring(a.length):b}for(var b=ga().split(","),d="",a="WIN ",e=0,f=b.length;e<f;e++)-1!=b[e].indexOf(a)?(d+=b[e].substring(a.length),d+="."):e==f-1?d+=b[e]:(d+=b[e],d+=".");return d}function X(){var a="",b;for(b in c)S(c[b])||
(""!=a&&(a+="&"),a+=b+"="+encodeURIComponent(c[b]));taqHome?(new Image(1,1)).src=taqHome+"/1.gif?"+a:s("no _taq.home!")}function Y(a){a=y.timing;try{if(0>=parseInt(a.loadEventEnd))setTimeout(function(){Y(c)},50);else{var b=a.domainLookupEnd-a.domainLookupStart,e=a.connectEnd-a.connectStart,d=a.responseStart-a.requestStart,f=a.domContentLoadedEventStart-a.fetchStart,g=a.responseEnd-a.navigationStart;-1!==l.navigator.userAgent.indexOf("Chrome")&&(c.p_fp=-1,l.chrome&&(msFirstPaint=l.chrome.loadTimes().firstPaintTime,
c.p_fp=0<=msFirstPaint?msFirstPaint:-1));-1!=navigator.appName.indexOf("Microsoft Internet Explorer")&&document.all&&(msFirstPaint=a.msFirstPaint-a.navigationStart,c.p_fp=0<=msFirstPaint?msFirstPaint:-1);requestType=y.navigation.type;var h=a.loadEventEnd-a.navigationStart;c.p_d=0<=b?b:-1;c.p_ct=0<=e?e:-1;c.p_st=0<=d?d:-1;c.p_nt=0<=g?g:-1;c.p_tt=0<=h?h:-1;c.p_dr=0<=f?f:-1;c.p_rt=requestType;c.p_c=0;1===requestType&&(c.p_c=0);0===a.requestStart&&(c.p_c=1);a.connectStart===a.connectEnd&&(c.p_c=1);if("getEntriesByType"in
y&&y.getEntriesByType("resource")instanceof Array){var k=y.getEntriesByType("resource");c.p_rc=k.length}X()}}catch(p){}}function ia(a){var b=a.getAttribute("data-trs-ta-event-key");if(null==b||"undefined"==b||""==b||"null"==b){for(;(a=a.parentNode)&&1==a.nodeType;)if(b=a.getAttribute("data-trs-ta-event-key"),null!=b&&"undefined"!=b&&""!=b&&"null"!=b)return a;return null}return a}function G(a){return null==a||"undefined"==a||""==a||"null"==a?a:a.replace(/\t/g," ").replace(/(^\s*)|(\s*$)/g,"").replace(/[\r\n]/g,
" ")}function e(a,b,c){null!=c&&"undefined"!=c&&""!=c&&"null"!=c&&(a+="&"+b+"="+c);return a}function Z(a,b){var f=r(b.href,255),d=r(b.id,255),g=r(G(b.innerText),255),h=r(b.type,255),k=r(b.name,255),m=r(b.target,255);a=e(a,"pv",c.pv);a=e(a,"e_id",d);a=e(a,"url",r(encodeURIComponent(document.URL)),1024);if("string"!=typeof f?0:0<f.length){a=e(a,"e_tu",encodeURIComponent(f));var d=f,p;null!=d&&"undefined"!=d&&""!=d&&"null"!=d&&(d=d.replace(/(^\s*)|(\s*$)/g,""));0==d.indexOf("http")||0==d.indexOf("https")?
(f=d.substring(0,d.indexOf("://")),d=d.substring(d.indexOf("://")+3),-1<d.indexOf("/")?p=d.substring(0,d.indexOf("/")):p=d):0==d.indexOf("//")?(f=null,d=d.substring(d.indexOf("//")+2),-1<d.indexOf("/")?p=d.substring(0,d.indexOf("/")):p=d):-1<d.indexOf(":")?(f=d.substring(0,d.indexOf(":")),p=null):(f=null,p=parseDomain2(document.URL));a=e(a,"e_td",encodeURIComponent(p));a=e(a,"e_tp",encodeURIComponent(f))}a=e(a,"e_tt",h);a=e(a,"e_tx",encodeURIComponent(g));a=e(a,"e_tn",k);return a=e(a,"e_ht",m)}function ja(a){var b=
ia(a.target||a.srcElement);if(null!=b){var g=b.tagName.toLowerCase();if("a"==g||"input"==g||"button"==g){var d=r(b.getAttribute("data-trs-ta-event-key"),255),h=r(b.getAttribute("data-trs-ta-event-type"),255),m=r(G(b.getAttribute("data-trs-ta-event-itemtype")),255),q=r(G(b.getAttribute("data-trs-ta-event-item")),255),s=r(G(b.getAttribute("data-trs-ta-event-itemname")),255),p,l,u;N?(l=Math.max(document.documentElement.scrollTop,document.body.scrollTop),p=Math.max(document.documentElement.scrollLeft,
document.body.scrollLeft),p=Math.floor(a.clientX+p),l=Math.floor(a.clientY+l)):(p=Math.floor(a.pageX),l=Math.floor(a.pageY));var w=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;0!=p&&0!=l&&(u=Math.floor(p-w/2));w=a.type;f=Z(f,b);f=e(f,"t_k",encodeURIComponent(d));f=e(f,"t_t",encodeURIComponent(h));f=e(f,"t_it",encodeURIComponent(m));f=e(f,"t_i",encodeURIComponent(q));f=e(f,"t_in",encodeURIComponent(s));f=e(f,"x",p);f=e(f,"y",l);f=e(f,"x2",u);f=e(f,"e_tn",g);f=
e(f,"e_et",w);(new Image(1,1)).src=f;f=$}}b=a.target||a.srcElement;if(null!=b){var g=r(b.tagName.toLowerCase(),255),v,n,x;N?(n=Math.max(document.documentElement.scrollTop,document.body.scrollTop),v=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),v=Math.floor(a.clientX+v),n=Math.floor(a.clientY+n)):(v=Math.floor(a.pageX),n=Math.floor(a.pageY));d=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;0!=v&&0!=n&&(x=Math.floor(v-d/2));"a"!=g&&"input"!=
g&&"button"!=g?(H+=1,D=""==D?"{"+v+","+n+","+x+"}":D+(";{"+v+","+n+","+x+"}"),10<=H&&(H=0,E+="&pa=["+D+"]",D="",v=new Image(1,1),v.src=E+"&pv="+c.pv,E=B+"&clicktype=1")):(d=r(a.type,255),t=Z(t,b),t=e(t,"e_et",d),t=e(t,"e_tn",g),t=e(t,"x",v),t=e(t,"y",n),t=e(t,"x2",x),v=new Image(1,1),v.src=t,t=B+"&clicktype=2")}var C,z,y;N?(z=Math.max(document.documentElement.scrollTop,document.body.scrollTop),C=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),C=Math.floor(a.clientX+C),z=Math.floor(a.clientY+
z)):(C=Math.floor(a.pageX),Math.floor(z=a.pageY));a=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;0!=C&&0!=z&&(y=Math.floor(C-a/2));I+=1;""==A?(A="{x:"+C+",y:"+z+"}",F="{z:"+y+",y:"+z+"}"):(A+=",{x:"+C+",y:"+z+"}",F+=",{z:"+y+",y:"+z+"}");10<=I&&(I=0,k+="&br="+J+"*"+K,k+="&pa=["+A+"]",k+="&pb=["+F+"]",F=A="",(new Image(1,1)).src=k,k=B+"&clicktype=3")}function ka(){if(""!=D){var a=new Image(1,1);a.src=E+="&pa=["+D+"]&pv="+c.pv;E=B+"&clicktype=1"}""!=A&&(k+="&br="+
J+"*"+K,k+="&pa=["+A+"]",k+="&pb=["+F+"]",F=A="",a=new Image(1,1),a.src=k,k=B)}function la(a){for(var b=".com.cn .net.cn .org.cn .gov.cn .edu.cn .com .cn .net .cc .org .tv .edu .mil .info .mobi .biz .pro .travel .museum .int .areo .post .rec".split(" "),c="",d=0;d<b.length;d++)if(c=b[d],-1!=a.indexOf(c)){a=a.replace(c,"");a=a.substring(a.lastIndexOf(".")+1,a.length);a+=c;break}return a}function O(a,b,c){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener&&a.addEventListener(b,c,!1)}var c={},
l=window;if(!l["ta.js"]){l["ta.js"]=!0;var L=l.location.hash.substring(1),L=fa(L,"heatShow"),g=document,w=!1;try{w=g.domain==top.document.domain}catch(ma){s("unable check top.document.domain: "+ma)}w=w?top.document:g;c.domain=w.domain||"";l&&l.screen&&(c.sh=l.screen.height||0,c.sw=l.screen.width||0,c.cd=l.screen.colorDepth||0);var m=g.getElementById("gscrumb");m&&(c.gc=u(m.innerHTML));var m=g.getElementById("NewsPaperName"),x=g.getElementById("NewsEditionName"),P=g.getElementById("NewsEditionNumber"),
aa=g.getElementById("NewsArticleTitle"),ba=g.getElementById("NewsArticleAuthor"),Q=g.getElementById("NewsArticleID"),ca=g.getElementById("NewsArticleTime");if(P||Q)m&&(c.a_pn=u(m.innerHTML)),x&&(c.a_ea=u(x.innerHTML)),P&&(c.a_en=u(P.innerHTML)),aa&&(c.a_nt=da(u(aa.innerHTML))),ba&&(c.a_ar=u(ba.innerHTML)),Q&&(c.a_id=u(Q.innerHTML)),ca&&(c.a_te=u(ca.innerHTML));if("undefined"!=typeof _taq){taqHome=_taq.home;for(var h in _taq)switch(_taq[h][0]){case "_mpId":c.mpId=_taq[h][1];break;case "_setUID":_taq[h][1]&&
""!=_taq[h][1]&&(c.uid=_taq[h][1])}}else{m=g.getElementById("_trs_ta_js");if(!m){s("not found _trs_ta_js script element, so just return!");return}x=m.src.split("?")[1].split("&");for(h in x)try{if("mpid"==x[h].split("=")[0]){c.mpId=x[h].split("=")[1];break}}catch(na){s("fail and skip, i="+h+", myselfSrcParamArray="+x)}taqHome=m.src.split("/js/")[0]}var q,n;c.pv=ea(c.mpId);0<g.cookie.length&&(q=T("_trs_ua_s_1"),n=T("_trs_uv"));V(q)&&(h=q,q=W(c.mpId),s("sessionCookie expired: "+h+", so create new: "+
q));V(n)&&(h=n,n=W(c.mpId),s("UVCookie expired: "+h+", so create new: "+n));h=new Date;h.setDate(h.getDate()+730);m=la(w.domain);U("_trs_uv",n,"/",h.toGMTString(),m);s("set UVCookie topLevelDomain: "+m+", _trs_uv="+n);m=new Date;m.setMinutes(m.getMinutes()+30);U("_trs_ua_s_1",q,"/",h.toGMTString());s("set sessionCookie: _trs_ua_s_1="+q);c.cs=q||"";c.cu=n||"";c.title=w.title||"";c.url=w.URL||"";c.refer=w.referrer||"";if(1==L){var M=document.createElement("iframe"),R;R=document.referrer&&"function"==
typeof document.referrer.indexOf&&0<=document.referrer.indexOf("/console/heatmap")?document.referrer.slice(0,document.referrer.indexOf("/console/heatmap")):taqHome;M.src=R+"/agent.html#"+document.documentElement.scrollWidth+"*"+document.documentElement.scrollHeight;document.body.appendChild(M);M.style.display="none";O(window,"resize",function(){M.src=R+"/agent.html?random="+Math.random()+"#"+document.documentElement.scrollWidth+"*"+document.documentElement.scrollHeight});L=0}navigator&&(c.lang=navigator.language||
navigator.browserLanguage||"",c.fl=ha(),c.je=navigator.javaEnabled()?1:0,c.ce=navigator.cookieEnabled?1:0);var y=l.performance;y?Y(c):X();var N=/msie (\d+\.\d+)/i.test(navigator.userAgent),$=taqHome+"/1.gif?event=click&sr="+screen.width+"*"+screen.height+"&url="+encodeURIComponent(document.URL),f=$,H=0,J=0,K=0,I=0;document.all||document.captureEvents(Event.MOUSEMOVE);J=document.documentElement&&document.documentElement.scrollWidth||document.body&&document.body.scrollWidth||0;K=document.documentElement&&
document.documentElement.scrollHeight||document.body&&document.body.scrollHeight||0;q=r(document.URL,1024);0<q.indexOf("#")&&(q=q.substring(0,q.indexOf("#")));var B=taqHome+"/1.gif?event=mousedown&sr="+screen.width+"*"+screen.height+"&br="+J+"*"+K+"&url="+encodeURIComponent(q),E=B+"&clicktype=1",t=B+"&clicktype=2",k=B+"&clicktype=3",D="",A="",F="";O(document,"mouseup",ja);O(window,"unload",ka)}})();
